### ISSUE TITLE
Center hold/roll head active needed

### ISSUE THREAD

**Issue by 1033Forest** [DarkBahamut162/global#1]
There's no graphic for it so it shows up as a blue X (or cut off depending on the quant of that hold), can that be fixed?

**Comment by DarkBahamut162** [comment]
This is an already "known issue" on my side. I wasn't working on it immediately since I was trying to cleanup and fully fix the diagonals (TopCap & BottomCap).

**Comment by DarkBahamut162** [comment]
UPDATE: I just added them and they seem to function properly.
